### PR TITLE
Update italian lang

### PR DESCRIPTION
**Pull request by mirkobrombin**
I fixed some problems with the Italian translation.

### CODE REVIEW

**Comment by Ragash** [comment]
Cool. I left some terms in english because they are now common in italian too, but well this is more polished

**Comment by mirkobrombin** [comment]
In Italy we use some of english terms  but only some :)

**Comment by Ragash** [comment]
I know, im Italian (and Named Mirko, also, lol) too.

**Comment by mirkobrombin** [comment]
lol incredible (ciao)

**Comment by ChrisBaines** [comment]
Thank you for the contribution @mirkobrombin

**Pull request merged**
